### ISSUE TITLE
This is unsafe!

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL22/solver-we-rebrainstormingamancalanameholdon#23]
Instead, consider using `catMaybes :: [Maybe a] -> [a]` 
https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Maybe.html#v:catMaybes

https://github.com/TU-CSCI2322-FL22/solver-we-rebrainstormingamancalanameholdon/blob/13f9bc092b4ade240ab21e3c841f256ff9fde388/Solver.hs#L40-L44

**Comment by sfogarty** [comment]
This looks like it is still in Milestone 3, so for full credit it should be fixed. However, it's not going to count for *that* much.

**Comment by leldridg** [comment]
wrote a custom instance of catMaybes, catMaybesTuples and deleted checkMove
