### ISSUE TITLE
If the current player has no beans, can the game crash?

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL22/solver-we-rebrainstormingamancalanameholdon#27]
https://github.com/TU-CSCI2322-FL22/solver-we-rebrainstormingamancalanameholdon/blob/873ccaa492dab8d5d19b8e7522511f1d71b58c5c/Mancala.hs#L83-L84

It seems possible for there to be no valid moves, but also the game not to be over. That might cause your code to crash.

**Comment by leldridg** [comment]
No. We don't think that can happen. Source: extensive hours of working on this project.
